name: Actualizar Choloretro

on:
  schedule:
    - cron: '30 4 * * *' # Ejecutar a las 4:30 AM
  workflow_dispatch:

jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Generar Catalogo Choloretro
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        ONEFICHIER_API_KEY: ${{ secrets.ONEFICHIER_API_KEY }}
        ONEFICHIER_FOLDER_ID: ${{ secrets.ONEFICHIER_FOLDER_ID }}
      run: python app/generate_choloretro.py

    - name: Empaquetar Repositorio (Zips y XML)
      run: python tools/create_repository.py

    - name: Commit y Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add catalog_choloretro.json cache_choloretro.db zips/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Choloretro catalog and repo" && git pull --rebase origin main && git push)
