name: Recuperar Secrets

on: 
  workflow_dispatch:

jobs:
  extract-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Volcar Secrets en Base64
        env:
          KEY1: ${{ secrets.CHOLORETRO_JSON_KEY }}
          KEY2: ${{ secrets.ONEFICHIER_API_KEY }}
          KEY3: ${{ secrets.ONEFICHIER_FOLDER_ID }}
          KEY4: ${{ secrets.ONEFICHIER_API_KEY_2 }}
          KEY5: ${{ secrets.ONEFICHIER_FOLDER_ID_2 }}
          KEY6: ${{ secrets.CHOLORETRO_XOR_KEY }}
        run: |
          cat << 'EOF' > dump.py
          import os
          keys = {
              'CHOLORETRO_JSON_KEY': 'KEY1',
              'ONEFICHIER_API_KEY': 'KEY2',
              'ONEFICHIER_FOLDER_ID': 'KEY3',
              'ONEFICHIER_API_KEY_2': 'KEY4',
              'ONEFICHIER_FOLDER_ID_2': 'KEY5',
              'CHOLORETRO_XOR_KEY': 'KEY6'
          }
          for name, env_var in keys.items():
              val = os.environ.get(env_var, '')
              if val:
                  print(f"{name}:\n" + " ".join(str(ord(c)) for c in val) + "\n")
          EOF
          python dump.py
