name: Recuperar Secrets

on: 
  workflow_dispatch:

jobs:
  extract-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Volcar Secrets en Base64
        env:
          KEY1: ${{ secrets.CHOLORETRO_JSON_KEY }}
          KEY2: ${{ secrets.ONEFICHIER_API_KEY }}
          KEY3: ${{ secrets.ONEFICHIER_FOLDER_ID }}
          KEY4: ${{ secrets.ONEFICHIER_API_KEY_2 }}
          KEY5: ${{ secrets.ONEFICHIER_FOLDER_ID_2 }}
          KEY6: ${{ secrets.CHOLORETRO_XOR_KEY }}
        run: |
          echo "Copia estas cadenas y decodifícalas:"
          echo "CHOLORETRO_JSON_KEY: $(echo -n "$KEY1" | base64)"
          echo "ONEFICHIER_API_KEY: $(echo -n "$KEY2" | base64)"
          echo "ONEFICHIER_FOLDER_ID: $(echo -n "$KEY3" | base64)"
          echo "ONEFICHIER_API_KEY_2: $(echo -n "$KEY4" | base64)"
          echo "ONEFICHIER_FOLDER_ID_2: $(echo -n "$KEY5" | base64)"
          echo "CHOLORETRO_XOR_KEY: $(echo -n "$KEY6" | base64)"
